apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../../apps/base/tap
- ../../../apps/base/tap-overlays
- values.yml

patchesStrategicMerge:
- sensitive-values.yml