apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../../apps/base/tap
- ../../../apps/base/tap-overlays
- values.yml

patches:
  - target:
      group: packaging.carvel.dev
      version: v1alpha1
      kind: PackageInstall
      name: tap
    patch: |-
      - op: add
        path: /spec/values/-
        value:
          secretRef:
            name: tap-sensitive-values
