---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: harbor-registry-creds
  namespace: tap-install
spec:
  secretStoreRef:
    name: tap-install
    kind: SecretStore
  refreshInterval: "1m"
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .registry | toString }}"
  data:
    - secretKey: registry
      remoteRef: 
        key: supplychain-registry-creds
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: harbor-registry-creds
  namespace: tap-install
spec:
  toNamespaces:
  - "*"

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gitops-secret
  namespace: tap-install
spec:
  secretStoreRef:
    name: tap-install
    kind: SecretStore
  refreshInterval: "1m"
  target:
    template:
      type: kubernetes.io/basic-auth
      metadata:
        annotations:
          tekton.dev/git-0: https://github.com
      data:
        password: "{{ .password | toString }}"
        username: "{{ .username | toString }}"
  data:
    - secretKey: username
      remoteRef: 
        key: github-user
    - secretKey: password
      remoteRef: 
        key: github-pat
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: gitops-secret
  namespace: tap-install
spec:
  toNamespaces:
  - "*"