---
apiVersion: v1
kind: Secret
metadata:
  name: tap-values
  namespace: tap-install
stringData:
  values.yaml: |
    profile: build
    amr:
      observer:
        auth:
          kubernetes_service_accounts:
            enable: true
        cloudevent_handler:
          endpoint: https://amr-cloudevent-handler.view.tap.azure.warroyo.com
    ceip_policy_disclosed: true
    deployed_through_tmc: true
    excluded_packages:
    - fluxcd.source.controller.tanzu.vmware.com
    namespace_provisioner:
      additional_sources:
      - git:
          ref: origin/main
          subPath: clusters/${cluster_name}/ns-provisioner/config
          url: https://github.com/warroyo/tap-flux-aks
        path: _ytt_lib/testing-scanning-supplychain-parameterized-setup
      controller: false
      default_parameters:
        supply_chain_service_account:
          secrets:
          - gitops-secret
      gitops_install:
        ref: origin/main
        subPath: clusters/${cluster_name}/ns-provisioner/namespaces
        url: https://github.com/warroyo/tap-flux-aks
    supply_chain: testing_scanning
    ootb_supply_chain_testing_scanning:
      carvel_package:
        workflow_enabled: true
        gitops_subpath: packages/base
        openapiv3_enabled: true
      image_scanner_template_name: image-vulnerability-scan-trivy
      image_scanning_cli:
        image: registry.tanzu.vmware.com/tanzu-application-platform/tap-packages@sha256:31d36a8582a75b042dc12aea0808f822e27747a2f8103af0f0c52ef8d68a8bf0
      gitops:
        commit_strategy: pull_request
        pull_request:
          commit_branch: ""
          pull_request_body: generated by supply chain
          pull_request_title: ready for review
          server_kind: github
        repository_name: tap-flux-aks
        repository_owner: warroyo
        server_address: https://github.com/
        credentials_secret: gitops-secret
    shared:
      image_registry:
        project_path: dev.registry.pivotal.io/warroyo
        secret:
          name: harbor-registry-creds
          namespace: tap-install
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-sensitive-values
  namespace: tap-install
spec:
  secretStoreRef:
    name: tap-install
    kind: SecretStore
  refreshInterval: "1m"
  data:
    - secretKey: sensitive-tap-values.yaml
      remoteRef:
        decodingStrategy: Base64
        key: tap-build-values