apiVersion: v1
kind: Secret
metadata:
  name: cert-man-azure-wi
  namespace: tap-install
  annotations:
    kapp.k14s.io/change-group: tap-overlays
type: Opaque
stringData:
  cert-man-azure-wi.yaml: |-
    #@ load("@ytt:overlay", "overlay")
    #@ load("@ytt:data", "data")
    #@overlay/match by=overlay.subset({"kind": "ServiceAccount", "metadata": {"name": "cert-manager" }}), expects=1
    ---
    metadata:
      #@overlay/match missing_ok=True
      labels:
        #@overlay/match missing_ok=True
        azure.workload.identity/use: "true"
    ---    
    #@overlay/match by=overlay.subset({"kind": "Deployment", "metadata": {"name": "cert-manager" }}), expects=1
    ---
    spec:
      template:
        metadata:
          #@overlay/match missing_ok=True
          labels:
            #@overlay/match missing_ok=True
            azure.workload.identity/use: "true"