apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: tap-install
  namespace: tap-install
spec:
  provider:
    # provider type: azure keyvault
    azurekv:
      # azure tenant ID, see: https://docs.microsoft.com/en-us/azure/active-directory/fundamentals/active-directory-how-to-find-tenant
      tenantId: "b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: 20220b3c-578d-4a2b-9257-8846aa958eab
  name: tap-akv-reader
  namespace: tap-install