---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: init-cluster-apps
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 10m0s
  path: clusters/${cluster_name}/init
  prune: true
  postBuild:
    substitute:
      cluster_name: ${cluster_name}
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tap-gitops

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: tap
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 10m0s
  path: clusters/${cluster_name}/tap
  prune: true
  postBuild:
    substitute:
      cluster_name: ${cluster_name}
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tap-gitops
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: post-tap
  namespace: tanzu-continuousdelivery-resources
spec:
  dependsOn:
    - name: tap
  interval: 10m0s
  path: clusters/${cluster_name}/post-tap
  prune: true
  postBuild:
    substitute:
      cluster_name: ${cluster_name}
  sourceRef:
    kind: GitRepository
    namespace: tanzu-continuousdelivery-resources
    name: tap-gitops