---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: external-dns-creds
  namespace: external-dns
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: cluster-wide-store

  target:
    name: route53-credentials
    creationPolicy: Owner

  data:
  # name of the SECRET in the Azure KV (no prefix is by default a SECRET)
  - secretKey: aws_access_key_id
    remoteRef:
      key: external-dns-access-key
  - secretKey: aws_secret_access_key
    remoteRef:
      key: external-dns-secret-key