apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 15m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: tanzu-continuousdelivery-resources
spec:
  targetNamespace: external-dns
  chart:
    spec:
      chart: external-dns
      version: 7.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-continuousdelivery-resources
  interval: 15m
  timeout: 5m
  releaseName: external-dns
  install:
    createNamespace: true
  values:
    sources:
    - contour-httpproxy
    provider: azure
    txtOwnerId: ${cluster_name}
    azure:
      useWorkloadIdentityExtension: true
      userAssignedIdentityID: da9cfb83-0587-4e3a-b472-8354b2bad2d5