apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: bitnami
  namespace: tanzu-continuousdelivery-resources
spec:
  interval: 15m
  url: https://charts.bitnami.com/bitnami
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: external-dns
  namespace: tanzu-continuousdelivery-resources
spec:
  targetNamespace: external-dns
  chart:
    spec:
      chart: external-dns
      version: 7.2.1
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: tanzu-continuousdelivery-resources
  interval: 15m
  timeout: 5m
  releaseName: external-dns
  install:
    createNamespace: true
  values:
    sources:
    - contour-httpproxy
    provider: azure
    txtOwnerId: ${cluster_name}
    azure:
      useWorkloadIdentityExtension: true
      resourceGroup: main-dns
      subscriptionId: 31f60aa7-0ea5-47af-85b2-27e792a36288
      tenantId: b39138ca-3cee-4b4a-a4d6-cd83d9dd62f0
    podLabels:
      azure.workload.identity/use: "true"
    serviceAccount:
      automountServiceAccountToken: true
      annotations:
        azure.workload.identity/client-id: d0a53e32-9176-4de7-b5d5-894cd42e1592