---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: tap-registry
  namespace: tap-install
spec:
  secretStoreRef:
    name: tap-install
    kind: SecretStore
  refreshInterval: "1m"
  target:
    template:
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ .registry | toString }}"
  data:
    - secretKey: registry
      remoteRef: 
        key: tap-registry-creds
---
apiVersion: secretgen.carvel.dev/v1alpha1
kind: SecretExport
metadata:
  name: tap-registry
  namespace: tap-install
spec:
  toNamespaces:
  - "*"