apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
generatorOptions:
  disableNameSuffixHash: true

resources:
- ../../../apps/base/cluster-name-secret/
- ../../../apps/base/external-secrets